apiVersion: v1
kind: Service
metadata:
  name: temperatura-api-svc
  labels:
    app: temperaturas-backend
spec:
  ports:
    - port: 5000
  selector:
    app: temperaturas-backend
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: temperatura-api-deploy
  labels:
    app: temperaturas-backend
spec:
  selector:
    matchLabels:
      app: temperaturas-backend
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: temperaturas-backend
        tier: backend
    spec:
      containers:
      - name: temperaturas-backend
        image: pcaamano/temperaturas-backend:latest
        ports:
        - containerPort: 5000