apiVersion: v1
kind: Service
metadata:
  name: temperatura-web-svc
  labels:
    app: temperaturas-frontend
spec:
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: temperaturas-frontend
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: temperatura-web-deploy
  labels:
    app: temperaturas-frontend
spec:
  selector:
    matchLabels:
      app: temperaturas-frontend
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: temperaturas-frontend
        tier: frontend
    spec:
      containers:
      - name: temperaturas-frontend
        image: pcaamano/temperaturas-frontend:latest
        ports:
        - containerPort: 3001